---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist:
- name: "Launchpad"
  pos: "after Finder"
- name: "Mission Control"
- name: "System Preferences"
  path: "/Applications/System Preferences.app/"
  pos: 4
- name: "Sequel Pro"
  path: "/Applications/Sequel Pro.app/"
  pos: 5
- name: "GitKraken"
  path: "/Applications/GitKraken.app/"
  pos: 6
- name: "Drafts"
  path: "/Applications/Drafts.app"
- name: "Visual Studio Code"
  pos: 7
  path: "/Applications/Visual Studio Code.app"
- name: "iTerm"
  pos: 8
  path: "/Applications/iTerm.app"
- name: "Google Chrome"
  pos: 9
  path: "/Applications/Google Chrome.app"
- name: "Safari"
  pos: 10
  path: "/Applications/Safari.app"
- name: "Airmail Beta"
  pos: 11
  path: "/Applications/Airmail Beta.app"
- name: "Messages"
  pos: 12
  path: "/Applications/Messages.app"
- name: "Messenger"
  pos: 13
  path: "/Applications/Messenger.app"
- name: "1Password"
  pos: 14
  path: "/Applications/1Password.app"
- name: "MoneyWiz"
  pos: 15
  path: "/Applications/MoneyWiz.app"
- name: "Home Assistant"
  pos: 16
  path: "/Applications/Home Assistant.app"
- name: "ScanSnap Home"
  pos: 17
  path: "/Applications/ScanSnap Home.app"
- name: "AnyDesk"
  pos: 18
  path: "/Applications/AnyDesk.app"
- name: "Feedback Assistant"
  pos: 19
  path: "/Applications/Feedback Assistant.app"

configure_sudoers: true
sudoers_custom_config: |
  '{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL'

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - rcmdnk/file/brew-file
  - ssh-copy-id
  - readline
  - openssl
  - pv
  - wget

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps: []

brewfile_git_repo: 'git jpartain89/brewfile-imac_desktop'

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: []
sublime_config_path: []
sublime_package_control: []
# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
