---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - name: OSx Command Line Tools
      import_role:
        name: elliotweiser.osx-command-line-tools

    - name: geerlingguy.mac.homebrew
      import_role:
        name: geerlingguy.mac.homebrew
      tags: ['homebrew']

    - name: brew-file.yml
      import_tasks: tasks/brew-file.yml
      tags: ['homebrew']

    - name: geerlingguy.mac.mas
      import_role:
        name: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']

    - name: geerlingguy.mac.dock
      import_role:
        name: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
