---

- name: Checking (and if not, overwriting) The BrewFile
  shell: '/usr/loca/bin/brew-file set_repo -r {{ brewfile_git_repo }}'

- name: Brew-file Pull
  shell: '/usr/loca/bin/brew-file pull'

- name: Running brew-file install
  shell: '/usr/local/bin/brew-file install'
