---

- name: Checking (and if not, overwriting) The BrewFile
  script: 'brew-file set_repo -r {{ brewfile_git_repo }}'

- name: Brew-file Pull
  shell: 'brew-file pull'

- name: Running brew-file install
  shell: 'brew-file install'
